// AMZN PAY SDK 2019-11-6 22:01:00
if (window.amazon == null || window.amazon.Login == null) {
(function() {
'use strict';var f,l,n,r,u,v;function aa(b,a){if(null===b||void 0===b)b={};for(var c=1;c<arguments.length;c++){var d=arguments[c];if(null!==d&&void 0!==d)for(var e in d)b[e]=d[e]}return b}function w(b,a){var c=z.apply(void 0,arguments);A("error",c);throw Error(c);}function ba(b,a){var c=z.apply(void 0,arguments);A("warn",c)}
function z(b,a){var c=arguments,d=1;return b.replace(/%((%)|[sid])/g,function(a){if(a[2])return a[2];a=c[d++];"object"==typeof a&&window.JSON&&window.JSON.stringify&&(a=window.JSON.stringify(a));return a})}function A(b,a){window.console&&window.console.log&&("function"==typeof a&&(a=a()),a=z("[Amazon.%s] %s",b,a),window.console.log(a))}function da(b){b&&"delegate"===b||w("expected %s value to be %s but was %s","options.response_type","delegate",b)}
function B(b,a,c){null==a&&w("missing %s",b);typeof a!=c&&w("expected %s to be a %s",b,c)}
function ea(b){var a=document.getElementById(b);a||(a=document.createElement("div"),a.setAttribute("id",b),a.setAttribute("width",0),a.setAttribute("height",0),a.setAttribute("style","position: absolute; left: -1000px; top: -1000px"),a.style.setAttribute&&a.style.setAttribute("cssText","position: absolute; left: -1000px; top: -1000px"),b=document.getElementById("amazon-root"),b||(b=document.createElement("div"),b.setAttribute("id","amazon-root"),document.body.appendChild(b)),b.appendChild(a));return a}
function fa(){var b=ea("amazon-client-credentials-root"),a=ma(16),c=document.createElement("iframe");c.setAttribute("name",a);b.appendChild(c);0==document.getElementsByName(a).length&&(b.removeChild(c),c=document.createElement('\x3ciframe name\x3d"'+a+'"/\x3e'),b.appendChild(c));c.setAttribute("id",a);return a}function C(){this.a=[]}C.prototype.wait=function(b,a){this.a.push({X:b,persist:!!a})};
C.prototype.b=function(b){var a=this.a;this.a=[];for(var c=0;c<a.length;c++)a[c].persist&&this.a.push(a[c]);for(c=0;c<a.length;c++)a[c].X.apply(void 0,arguments)};
var D=function(){function b(){switch(g){case "t":return e("t"),e("r"),e("u"),e("e"),!0;case "f":return e("f"),e("a"),e("l"),e("s"),e("e"),!1;case "n":return e("n"),e("u"),e("l"),e("l"),null}h("Unexpected '"+g+"'")}function a(){for(;g&&" ">=g;)e()}function c(){var a,b="",c;if('"'===g)for(;e();){if('"'===g)return e(),b;if("\\"===g)if(e(),"u"===g){for(a=c=0;4>a;a+=1){var d=parseInt(e(),16);if(!isFinite(d))break;c=16*c+d}b+=String.fromCharCode(c)}else if("string"===typeof m[g])b+=m[g];else break;else b+=
g}h("Bad string")}function d(){var a="";"-"===g&&(a="-",e("-"));for(;"0"<=g&&"9">=g;)a+=g,e();if("."===g)for(a+=".";e()&&"0"<=g&&"9">=g;)a+=g;if("e"===g||"E"===g){a+=g;e();if("-"===g||"+"===g)a+=g,e();for(;"0"<=g&&"9">=g;)a+=g,e()}a=+a;if(isFinite(a))return a;h("Bad number")}function e(a){a&&a!==g&&h("Expected '"+a+"' instead of '"+g+"'");g=q.charAt(k);k+=1;return g}function h(a){throw{name:"SyntaxError",message:a,la:k,text:q};}var k,g,m={'"':'"',"\\":"\\","/":"/",ma:"\b",na:"\f",n:"\n",r:"\r",t:"\t"},
q;var y=function(){a();switch(g){case "{":a:{var m={};if("{"===g){e("{");a();if("}"===g){e("}");var k=m;break a}for(;g;){k=c();a();e(":");Object.hasOwnProperty.call(m,k)&&h('Duplicate key "'+k+'"');m[k]=y();a();if("}"===g){e("}");k=m;break a}e(",");a()}}h("Bad object");k=void 0}return k;case "[":a:{k=[];if("["===g){e("[");a();if("]"===g){e("]");break a}for(;g;){k.push(y());a();if("]"===g){e("]");break a}e(",");a()}}h("Bad array");k=void 0}return k;case '"':return c();case "-":return d();default:return"0"<=
g&&"9">=g?d():b()}};return function(b,c){q=b;k=0;g=" ";b=y();a();g&&h("Syntax error");return"function"===typeof c?function J(a,b){var d,e=a[b];if(e&&"object"===typeof e)for(d in e)if(Object.prototype.hasOwnProperty.call(e,d)){var g=J(e,d);void 0!==g?e[d]=g:delete e[d]}return c.call(a,b,e)}({"":b},""):b}}(),F=function(){function b(a){return 10>a?"0"+a:a}function a(a){d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var b=k[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function c(b,d){var k=e,m=d[b];m&&"object"===typeof m&&"function"===typeof m.toJSON&&(m=m.toJSON(b));"function"===typeof g&&(m=g.call(d,b,m));switch(typeof m){case "string":return a(m);case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);case "object":if(!m)return"null";e+=h;var q=[];if("[object Array]"===Object.prototype.toString.apply(m)){var E=m.length;for(b=0;b<E;b+=1)q[b]=c(b,m)||"null";d=0===q.length?"[]":e?"[\n"+e+q.join(",\n"+e)+"\n"+
k+"]":"["+q.join(",")+"]";e=k;return d}if(g&&"object"===typeof g)for(E=g.length,b=0;b<E;b+=1){if("string"===typeof g[b]){var x=g[b];(d=c(x,m))&&q.push(a(x)+(e?": ":":")+d)}}else for(x in m)Object.prototype.hasOwnProperty.call(m,x)&&(d=c(x,m))&&q.push(a(x)+(e?": ":":")+d);d=0===q.length?"{}":e?"{\n"+e+q.join(",\n"+e)+"\n"+k+"}":"{"+q.join(",")+"}";e=k;return d}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+
1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var d=/[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,h,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;return function(a,b,d){var k;h=e="";if("number"===typeof d)for(k=
0;k<d;k+=1)h+=" ";else"string"===typeof d&&(h=d);if((g=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})}}();function K(b){var a="",c;for(c in b)a&&(a+="\x26"),a+=encodeURIComponent(c)+"\x3d"+encodeURIComponent(b[c]+"");return a}
(function(){function b(a,b){for(var c=0;c<b.length;c++){var e=b[c];""==e||a.b.hasOwnProperty(e)||(a.a.push(e),a.b[e]=1)}}l=function(a){this.a=[];a="string"==typeof a?a.split(/\s+/):a;this.b={};b(this,a)};l.prototype.contains=function(a){for(var b=0;b<a.a.length;b++)if(!this.b.hasOwnProperty(a.a[b]))return!1;return!0};l.prototype.add=function(a){b(this,a.a)};l.prototype.c=function(a){for(var b=0;b<this.a.length;b++)a(this.a[b])};l.prototype.toString=function(){return this.a.join(" ")}})();
(function(){n={};var b=null;n.m=function(){return b};n.o=function(a){B("domain",a,"string");a=a.replace(/^\s+|\s+$/g,"");var c="."+window.location.hostname;"."!=a.charAt(0)&&(a="."+a);c.indexOf(a)!=c.length-a.length&&w("Site domain must contain the current page's domain");b=a};n.v=function(){};n.v.prototype.getItem=function(){};n.v.setItem=function(){};n.v.removeItem=function(){}})();
(function(){function b(){}b.prototype.getItem=function(a){a=(new RegExp("(?:^|;)\\s*"+escape(a).replace(/[\-\.\+\*]/g,"\\$\x26")+"\\s*\\\x3d\\s*([^;]*)(?:;|$)")).exec(document.cookie);return null==a?null:unescape(a[1])};b.prototype.setItem=function(a,b,d){var c=null==d?"Fri, 31 Dec 9999 23:59:59 GMT":(new Date((new Date).getTime()+1E3*d)).toGMTString();var h=n.m();h=null==h?"":";Domain\x3d"+h;var k=qa(M(window.location.href))?"":";Secure";document.cookie=a+"\x3d"+escape(b)+("session"==d?"":";Expires\x3d"+
c)+h+";Path\x3d/"+k};b.prototype.removeItem=function(a){n.f.setItem(a,"null",0)};n.f=new b})();(function(){function b(a){this.a=a}b.prototype.getItem=function(a){return this.a.getItem(a)};b.prototype.setItem=function(a,b,d){this.a.setItem(a,b,d)};b.prototype.removeItem=function(a){n.f.removeItem(a)};n.l=new b(n.f)})();
(function(){function b(a){try{var b=D(a).clear}catch(e){b=void 0}b&&(console.log("Deleting cache cookie now."),n.l.removeItem("amazon_Login_state_cache"))}r={};var a=/.*(eu|apac).*(account).*/;r.I=function(a,b){"bearer"==a.token_type&&(a={access_token:a.access_token,max_age:b,expiration_date:(new Date).getTime()+1E3*b,client_id:u.K(),scope:a.scope},N()&&(a.domain=u.m()),a=F(a),n.l.setItem("amazon_Login_state_cache",a,"session"))};r.A=function(){var a=n.l.getItem("amazon_Login_state_cache");if(null!=
a&&(a=D(a),null!=a&&a.expiration_date>(new Date).getTime())){if(N()&&"undefined"!=typeof a.domain&&a.domain!=u.m())return null;a.scope=new l(a.scope);return a}return null};r.W=function(){var c=O(u.B(),"/checkout/clear",null,null).toString();if(!c.match(a)){var d="?coe\x3d"+u.J()+"\x26env\x3d"+u.L();if(window.XDomainRequest){var e=new window.XDomainRequest;e.onload=function(){b(e.responseText)}}else{var h=!1;e=new window.XMLHttpRequest;e.onreadystatechange=function(){h||4!=e.readyState||(h=!0,b(e.responseText))}}e.open("GET",
c+d,!0);e.withCredentials=!0;e.send(null)}};r.w=function(){n.l.removeItem("amazon_Login_state_cache")}})();function ra(){return window.XMLHttpRequest&&"withCredentials"in new window.XMLHttpRequest||"undefined"!==typeof window.XDomainRequest?!0:!1}
function P(b,a,c,d,e,h){this.a=new Q(b,a,c);"string"==typeof d&&d||w("missing or invalid path: %s",d);this.i=d;"object"==typeof e&&(e=K(e));e&&"string"!=typeof e&&w("invalid query: %s",e);this.c=e||"";"object"==typeof h&&(h=K(h));h&&"string"!=typeof h&&w("invalid fragment: %s",h);this.b=h||""}
function M(b){var a=function(){var a=document.createElement("div");a.innerHTML="\x3ca\x3e\x3c/a\x3e";a.firstChild.href=b;a.innerHTML=a.innerHTML;return a.firstChild}();""==a.host&&(a.href=a.href);return new P(a.protocol,a.hostname,function(){var b=a.port;b&&"0"!=b||(b=null);return b}(),function(){var b=a.pathname;b?"/"!=b[0]&&(b="/"+b):b="/";return b}(),a.search.substring(1),a.href.split("#")[1]||"")}f=P.prototype;f.scheme=function(){return this.a.scheme()};f.host=function(){return this.a.host()};
f.port=function(){return this.a.port()};f.path=function(){return this.i};f.query=function(){return this.c};f.h=function(){return this.b};function qa(b){var a="http"==b.a.scheme();b=b.a.host();return a&&("localhost"==b||"127.0.0.1"==b)}f.toString=function(){var b=this.a.toString();b+=this.i;b+=this.c?"?"+this.c:"";return b+=this.b?"#"+this.b:""};
function sa(b,a){return new P(void 0!==a.scheme?a.scheme:b.scheme(),void 0!==a.host?a.host:b.host(),void 0!==a.port?a.port:b.port(),void 0!==a.path?a.path:b.path(),void 0!==a.query?a.query:b.query(),void 0!==a.h?a.h:b.h())}
function Q(b,a,c){var d;"string"==typeof b&&(d=b.match(/^(https?)(:(\/\/)?)?$/i))||w("missing or invalid scheme: %s",b);this.a="http"==d[1]?"http":"https";if(b="string"==typeof a&&a)"string"==typeof a&&a||w("missing or invalid input: %s",a),b=0!=a.replace(/^\s+|\s+$/g,"").length;b||w("missing or invalid host: %s",a);this.c=a;c&&((c+"").match(/^\d+$/)||w("invalid port: %s",c),80==c&&"http"==this.a||443==c&&"https"==this.a)&&(c=null);this.b=c?c+"":null}var ta=/^(http|https):\/\/(.+?)(:(\d+))?$/i;
Q.prototype.scheme=function(){return this.a};Q.prototype.host=function(){return this.c};Q.prototype.port=function(){return this.b};Q.prototype.toString=function(){var b=this.a+"://";b+=this.c;return b+=this.b?":"+this.b:""};function O(b,a,c,d){return new P(b.a,b.c,b.b,a,c,d)}function ma(b){for(var a="",c=0;c<b;c++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return a}var R={},S=null;
function ua(b,a,c){if(window.__toucanForceProxyOriginTo){b=window.__toucanForceProxyOriginTo;var d=b.match(ta);if(d)b=new Q(d[1],d[2],d[4]?d[4]-0:null);else throw w("invalid origin: %s",b),Error();}else if(window.__toucanForceProxyOriginToThisOrigin)b=M(window.location.href).a;else if(d=b.host().match(/^([\w\-\.]+\.)?amazon\.([\w\.]+)$/))d="api-cdn.amazon."+d[2],a&&(d=b.host()),"https"==b.scheme()?b=new Q("https",d,null):(w("no proxy origin; unsupported non-https target origin for amazon: %s",b),
b=void 0);else throw w("no proxy origin; unsupported target origin: %s",b),Error();d=va(b);var e=b;if(a)var h="amazon-proxy-iframe-name";else h=e.host().replace(/[^a-z0-9]/ig,"_"),e.port()&&(h+="_"+e.port()),h=z("amazon-proxy-%s-%s",e.scheme(),h);var k=document.getElementById(h);k||(k=document.createElement("iframe"),k.setAttribute("id",h),k.setAttribute("name",h),k.setAttribute("src",ya(e,d,a).toString()),ea("amazon-proxy-root").appendChild(k));a=h;d=ma(16);R[d]||(R[d]=new C);R[d].wait(c,!1);c=b;
a={uri:Ca().toString(),proxy:a,topic:d,version:"1"};return O(c,"/sdk/2018-02-08-63k6q26l/topic.html",a,"")}function va(b){S||(S=Da(),S.N(b,function(a,b){(a=R[a])&&a.b(b)}));return S}function Ca(){return sa(M(window.location.href),{query:"",h:""})}function ya(b,a,c){a={uri:Ca().toString(),tr:a.name()};return O(b,(c?"/static/sdk":"/sdk/2018-02-08-63k6q26l")+"/proxy.html",c?"":{version:"1"},a)}var Ea=/^ABMNZNXDC;([\w\d_\-]+);(.*)$/;
function Fa(b){var a=b.match(Ea);if(a){b={};b.id=a[1];var c={};a=a[2].split("\x26");for(var d=0;d<a.length;d++){var e=a[d].split("\x3d");2==e.length&&(c[e[0]]=decodeURIComponent(e[1].replace(/\+/g," ")))}b.data=c;return b}return null}function Da(){var b=window.postMessage?"pm":"fr";window.__toucanForceTransport&&(b=window.__toucanForceTransport);if("pm"==b)b=new Y;else if("fr"==b)b=new Z;else throw w("unknown transport: %s",b),Error();return b}var Ia={pm:"ACCESS_TOKEN_RECEIVED_PM",fr:"ACCESS_TOKEN_RECEIVED_FR"};
function Y(){this.a=void 0}Y.prototype.name=function(){return"pm"};function Ja(b){if(void 0===b.a){var a=b.a=new C;b=function(b){var c;(c=Fa(b.data))&&a.b(b.origin,c.id,c.data)};window.addEventListener?window.addEventListener("message",b,!1):window.attachEvent?window.attachEvent("onmessage",b):w("cannot attach message event")}}
Y.prototype.N=function(b,a){Ja(this);var c=b.toString();this.a.wait(function(b,e,h){var d=M(window.location.href).a.toString();if(b!=c&&b!=d)ba("Either message from %s does not match proxy origin %s or message from %s does not match current window origin %s",b,c,b,d);else{if(h&&h.method&&Ia[h.method]){d=Ia[h.method];b=O(u.B(),"/checkout/authui/sysmetrics",null,null).toString();d="?metrics\x3d"+d;var g=new window.XMLHttpRequest;g.open("POST",b+d,!0);g.send(F({}))}a(e,h)}},!0)};
Y.prototype.send=function(b,a,c){var d=b.a,e=D(F(c));setTimeout(function(){window.parent.postMessage(z("%s;%s;%s","ABMNZNXDC",a,K(e)),d.toString())},1)};function Z(){}Z.prototype.name=function(){return"fr"};Z.prototype.N=function(b,a){window.__toucanInvokeFragment=function(b,d){a(b,d)}};
Z.prototype.send=function(b,a,c){var d=b.query();(d=d||"")&&(d+="\x26");d=d+"ABMNZNXDC"+("\x3d"+ma(8));b=sa(b,{query:d,h:z("%s;%s;%s","ABMNZNXDC",a,K(c))});a=document.createElement("iframe");a.setAttribute("src",b.toString());document.body.appendChild(a)};var Ka=window.location.href.split("#")[1]||"";if(Ka){var La=Fa(Ka);La&&(document.documentElement.style.display="none","function"==typeof window.parent.parent.__toucanInvokeFragment&&window.parent.parent.__toucanInvokeFragment(La.id,La.data))}
(function(){function b(a){var b=a.match(Ha);b||w("invalid domain: %s",a);var p=b[2]?b[2].toLowerCase():"https";"https"!=p&&w("invalid domain: %s; scheme must be https",a);a=b[3];a.match(/^amazon\.[a-z\.]+$/)&&(a="www."+a);return new Q(p,a,b[5])}function a(a){a=aa({interactive:void 0,popup:!0,response_type:"token",response_mode:void 0,delegated_requests:void 0,direct_post_uri:void 0,state:void 0,scope:void 0,scope_data:void 0,optional_scope:void 0,"com.amazon.oauth2.options":void 0,workflow_data:void 0},
a||{});B("options.response_type",a.response_type,"string");a.response_mode&&B("options.response_mode",a.response_mode,"string");a.direct_post_uri&&B("options.direct_post_uri",a.direct_post_uri,"string");var b=a.delegated_requests;if(b){da(a.response_type);a.scope&&w("options.scope is not supported for delegated authorization");a.scope_data&&w("options.scope_data is not supported for delegated authorization");a.optional_scope&&w("options.optional_scope is not supported for delegated authorization");
a.interactive?a.interactive!=t.ALWAYS&&w("options.interactive should be '"+t.ALWAYS+"' for delegated authorization"):a.interactive=t.ALWAYS;for(var p={},g=0;g<b.length;g++){var k=b[g],m=c(a,k);p[k.request_id]=m}a.delegated_requests=p}else if(d(a,"missing options.scope"),e(a),h(a),a.interactive?a.interactive!=t.s&&a.interactive!=t.ALWAYS&&a.interactive!=t.NEVER&&w("expected options.interactive to be one of '"+t.s+"', '"+t.ALWAYS+"', or '"+t.NEVER+"'"):a.interactive=t.s,a.optional_scope){a.optional_scope.constructor!==
Array&&"string"!=typeof a.optional_scope&&w("expected options.optional_scope to be a string or array");a.interactive!=t.NEVER&&w("options.optional_scope is only supported for options.interactive \x3d never");b=new l(a.optional_scope);a.scope.add(b);var q={id_token:{}};b.c(function(a){q.id_token[a]={essential:!1}});a.optional_scope=F(q)}return a}function c(a,b){b.response_mode&&w("response_mode is not supported in delegated requests");b.direct_post_uri&&w("direct_post_uri is not supported in delegated requests");
"popup"in b&&w("popup is not supported in delegated requests");b.interactive&&w("interactive mode is not supported in delegated requests");b.optional_scope&&w("optional_scope is not supported in delegated requests");b.delegated_requests&&w("delegated_requests is not supported in delegated requests");null==b.response_type&&(b.response_type="token");d(b,"missing 'scope' in delegated request");b.scope=b.scope.toString();e(b);h(a);B("request_id",b.request_id,"string");b.client_id&&!b.client_id.match(pa)&&
w("invalid client_id format: %s",b.client_id);a={};for(var p in b)"request_id"!=p&&(a[p]=b[p]);return a}function d(a,b){a.scope||w(b);a.scope.constructor!==Array&&"string"!=typeof a.scope&&w("expected scope to be a string or array");a.scope=new l(a.scope)}function e(a){a.scope_data&&(a.scope_data=F(a.scope_data))}function h(a){if(a.workflow_data){var b={};b.workflow_data=a.workflow_data;a["com.amazon.oauth2.options"]=F(b)}}function k(a){a=parseInt(a.expires_in,10);return 60>=a?a:a-Math.min(Math.floor(.1*
a),300)}function g(a){var b=(void 0!==window.screenX?window.screenX:window.screenLeft)+Math.floor(((void 0!==window.outerWidth?window.outerWidth:document.documentElement.clientWidth)-800)/2),c=(void 0!==window.screenY?window.screenY:window.screenTop)+Math.floor(((void 0!==window.outerHeight?window.outerHeight:document.documentElement.clientHeight)-660)/2);b=z("left\x3d%s,top\x3d%s,width\x3d%s,height\x3d%s,resizable\x3d1,scrollbars\x3d1",0>b?0:b,0>c?0:c,800,Math.min(660,void 0!==window.screen.availHeight?
window.screen.availHeight-100:window.screen.height-150));L=window.open(a.toString(),"amazonloginpopup",b)}function m(){null!=L&&("function"==typeof L.close&&L.close(),L=null)}function q(a,b,c,d,e){b={client_id:T,redirect_uri:b,response_type:a.response_type,language:wa,ui_locales:xa};a["com.amazon.oauth2.options"]&&(b["com.amazon.oauth2.options"]=a["com.amazon.oauth2.options"]);a.response_mode&&(b.response_mode=a.response_mode);a.scope&&(b.scope=a.scope.toString());a.direct_post_uri&&(b.direct_post_uri=
a.direct_post_uri);a.scope_data&&(b.scope_data=a.scope_data);ha&&(b.sandbox=!0);a.state&&(b.state=a.state);c&&(b.exac=c,e&&(b.exacde=d));a.delegated_requests&&(b.delegated_requests=F(a.delegated_requests));e&&(b.coe=U,b.ledger_currency=ia,b.env=V,b.is_itp_request=!0,b.origin_url=window.location.href);G=Ma(oa,!e);return e?O(H,G,b):O(I,G,b)}function y(a,b,c){W=!1;null!=b.access_token?(c=k(b),r.I(b,c),u.S()?n.f.setItem(u.g,b.access_token,c):n.f.removeItem(u.g)):c&&n.f.removeItem(u.g);a.M(b);a=ja;ja=
[];for(b=0;b<a.length;b++)E(a[b])}function na(a,b,c,d){var e=K(a);!c&&d?(a=M(b),a=sa(a,{h:e})):(b+=-1==b.indexOf("?")?"?":"\x26",b+=e,a=M(b));e=M(window.location.href);"https"==a.scheme()||qa(a)||w("attempted redirect to %s but scheme is not HTTPS",b);a.host()!=e.host()&&w("attempted redirect to %s but it does not match current host %s",a.host(),e.host());!c&&d?window.top.location.href=a.toString():(m(),window.location.href=b)}function ca(a){var b=this;this.a=a;this.c=null;this.C=[];this.i=null;this.b=
{status:null,onComplete:function(a){"string"!=typeof a&&"function"!=typeof a&&w("onComplete expects handler parameter to be a function or a string");var c=b.b.status==X.G;"string"==typeof a?c?na(b.i,a,b.a.popup,"token"==b.a.response_type):b.c=a:"function"==typeof a&&(c?setTimeout(function(){a(b.b)},0):b.C.push(a));return b.b}}}function E(a){var b=a.a,c=null;c=!b.popup;var d=Na(b.scope,c,c?a.c:null,c?window.location.hostname:null,"token"==b.response_type);if(b.delegated_requests)x(a,null,0,!1);else{if(b.interactive==
t.ALWAYS)r.w();else{var e=null,g=null;u.S()&&(e=n.f.getItem(u.g));if(c=r.A())"token"==b.response_type&&b.scope.add(c.scope),e?e!=c.access_token&&(r.w(),c=null):(e=c.access_token,g=c.expiration_date);if(c&&c.scope.contains(b.scope)&&"token"==b.response_type){var p={access_token:c.access_token,token_type:"bearer",expires_in:Math.floor((c.expiration_date-(new Date).getTime())/1E3),scope:c.scope.toString()};null!=b.state&&(p.state=b.state)}else if(b.interactive==t.NEVER&&b.popup){if(W){ja.push(a);a.D(X.U);
return}if(e){Ga(a,e,g,d);return}p={error:"invalid_grant",error_description:"invalid grant"}}if(p){setTimeout(function(){a.M(p)},0);return}}x(a,e,g,d)}}function x(a,b,c,d){var e=a.a;if(e.popup)W=!0,e=ua(d?H:I,d,function(b){m();y(a,b,!0)}),b=q(a.a,e,b,c,d),g(b,a);else{var p=a.c;p||w("Missing redirectUrl for redirect flow");window.top.location.href=q(e,M(p+""),b,c,d).toString()}}function Ga(a,b,c,d){W=!0;var e=ea("amazon-client-credentials-root"),g=fa(),p=document.createElement("form");e.appendChild(p);
p.setAttribute("method","POST");p.setAttribute("target",g);var h=a.a,k=ua(d?H:I,d,function(b){e.removeChild(p);var c=document.getElementById(g);null!=c&&null!=c.parentNode&&c.parentNode.removeChild(c);null==b&&(b={error:"server_error",description:"Server error."});y(a,b,!1)});b={client_id:T,exac:b,grant_type:"client_credentials",redirect_uri:k,response_type:h.response_type,scope:h.scope};null!=h.state&&(b.state=h.state);null!=h.response_mode&&(b.response_mode=h.response_mode);null!=h.direct_post_uri&&
(b.direct_post_uri=h.direct_post_uri);null!=h.scope_data&&(b.scope_data=h.scope_data);null!=h.optional_scope&&(b.claims=h.optional_scope);null!=h["com.amazon.oauth2.options"]&&(b["com.amazon.oauth2.options"]=h["com.amazon.oauth2.options"]);d&&(b.exacde=c,b.coe=U,b.ledger_currency=ia,b.env=V,b.is_itp_request=!0);G=Ma(oa,!d);c=d?O(H,G,b).toString():O(I,G,b).toString();p.setAttribute("action",c);p.submit()}u={V:{NorthAmerica:"NA",Europe:"EU",AsiaPacific:"APAC",UnitedStates:"US",UnitedKindom:"UK",Germany:"DE",
Italy:"IT",France:"FR",Spain:"ES",Japan:"JP"},u:[],g:"amazon_Login_accessToken"};var J={NA:["https://na.account.amazon.com","https://api.amazon.com"],EU:["https://eu.account.amazon.com","https://api.amazon.co.uk"],APAC:["https://apac.account.amazon.com","https://api.amazon.co.jp"],US:["https://payments.amazon.com","https://api.amazon.com"],UK:["https://pay.amazon.co.uk","https://api.amazon.co.uk"],DE:["https://pay.amazon.de","https://api.amazon.co.uk"],IT:["https://pay.amazon.it","https://api.amazon.co.uk"],
FR:["https://pay.amazon.fr","https://api.amazon.co.uk"],ES:["https://pay.amazon.es","https://api.amazon.co.uk"],JP:["https://pay.amazon.co.jp","https://api.amazon.co.jp"]},oa={lwa_general:"/ap/oa",connectedAuth_general:"/checkout/authCreate"},pa=/^[\w\-\.]+$/,Ha=/^((http|https):\/\/)?([a-z0-9\-\.]+)(:(\d+))?\/?$/i,t={ALWAYS:"always",s:"auto",NEVER:"never"},L=null,W=!1,ja=[],X={U:"queued",T:"in_progress",G:"complete"},T=void 0,U=void 0,ia=void 0,za=void 0,V=void 0,G="/ap/oa";u.j=function(a){0>u.u.indexOf(a)&&
u.u.push(a)};u.K=function(){u.j("getClientId-api-metric");return T};u.da=function(a){a.match(pa)||w("invalid client ID: %s",a);T=a};u.R=function(a,b,c){U=a;ia=b;V=c};u.ga=function(a){za=a};u.$=function(){return za};var ka="na.account.amazon.com",la="na.account.amazon.com",H=new Q("https",ka,null),I=new Q("https",la,null),Aa=new Q("https","api.amazon.com",null);u.m=function(){return ka};u.oa=function(){return la};u.Y=function(){return Aa};u.J=function(){return U};u.L=function(){return V};var ha=!1;
u.ia=function(a){"number"==typeof a&&(a=!!a);B("sandboxMode",a,"boolean");ha=a};u.aa=function(){return ha};u.o=function(a){H=b(a);ka=a};u.P=function(a){I=b(a);la=a};u.F=function(a){u.j("setAPIDomain-api-metric");Aa=b(a)};u.ha=function(a){u.j("setRegion-api-metric");var b;a&&(b=a.toUpperCase());b&&b in J?2==J[b].length?u.F(J[b][1]):w("missing domain or api domain configuration for given region."):(u.o("https://na.account.amazon.com"),u.P("https://na.account.amazon.com"),u.F("https://api.amazon.com"))};
u.ka=function(){r.W()};var wa="";u.ea=function(a){u.j("setLanguage-api-metric");wa=a};var xa="";u.fa=function(a){u.j("setLanguageHint-api-metric");xa=a};u.B=function(){return H};u.Z=function(){return I};var Ba=!1;u.S=function(){return Ba};u.ja=function(a){null==a?w("missing useCookie"):"number"==typeof a?a=!!a:"boolean"!=typeof a&&w("expected useCookie to be a boolean");Ba=a};ca.prototype.M=function(a){this.i=a;aa(this.b,a);this.D(X.G);for(a=0;a<this.C.length;a++)this.C[a](this.b);null!=this.c&&na(this.i,
this.c,this.a.popup,"token"==this.a.response_type)};ca.prototype.D=function(a){this.b.status=a};u.H=function(b,c){"undefined"!==typeof window.OffAmazonPayments&&"undefined"!==typeof window.OffAmazonPayments.Widgets&&"undefined"!==typeof window.OffAmazonPayments.Widgets.Utilities&&window.OffAmazonPayments.Widgets.Utilities.setLoginDomain("");2>arguments.length&&w("authorize expects two arguments (options, next)");b&&"object"!=typeof b&&w("authorize expects options parameter to be an object");null!=
c&&"function"!=typeof c&&"string"!=typeof c&&w("authorize expects next parameter to be a function or a string");b=a(b);var d=new ca(b),e=d.b;d.D(X.T);if(null!=c)e.onComplete(c);b.popup||"string"==typeof c?E(d):w("next must be redirect URI if !options.popup");return e};u.ca=function(a){a=Fa(a);return null!=a&&a.data&&null!=a.data.access_token?(r.I(a.data,k(a.data)),null!=r.A()):!1}})();
(function(){function b(a,b){try{var c=D(a)}catch(e){c=null}c&&c.Error?(a={success:!1},a.error=z("%s: %s",c.Error.Code||"UnknownError",c.Error.Message||"An unknown error occurred"),b(a)):c&&c.Profile?(a={success:!0},a.profile=c.Profile,b(a)):(a={success:!1,error:"UnknownError: Incomprehensible response from profile endpoint"},b(a))}v={O:function(a,c){if(null==c&&"function"==typeof a)c=a,u.H({scope:"profile"},function(a){null==a.error?v.O(a.access_token,c):c({success:!1,error:a.error})});else if(B("accessToken",
a,"string"),B("callback",c,"function"),ra()){a=O(u.Z(),"/ap/user/profile",{access_token:a},"").toString();if(window.XDomainRequest){var d=new window.XDomainRequest;d.onload=function(){b(d.responseText,c)}}else{var e=!1;d=new window.XMLHttpRequest;d.onreadystatechange=function(){e||4!=d.readyState||(e=!0,b(d.responseText,c))}}d.open("GET",a,!0);d.send()}else c({success:!1,error:"UnsupportedOperation: Cannot retrieve profile in this browser"})}}})();
(function(){function b(a){var b=O(u.B(),"/checkout/logout",null,null).toString(),e="?coe\x3d"+u.J()+"\x26env\x3d"+u.L()+"\x26mID\x3d"+u.$();if(window.XDomainRequest){var d=new window.XDomainRequest;d.onload=function(){c(d.responseText,a)}}else{var h=!1;d=new window.XMLHttpRequest;d.onreadystatechange=function(){h||4!=d.readyState||(h=!0,c(d.responseText,a))}}d.open("GET",b+e,!1);d.withCredentials=!0;d.send(null)}function a(a,b){ra()||e("UnsupportedOperation: Cannot remotely logout in this browser",
b);var c=O(u.Y(),"/auth/relyingPartyLogout",null,null).toString(),h={};h.token=a;h.token_type="bearer";if(window.XDomainRequest){var k=new window.XDomainRequest;k.onload=function(){d(k.responseText,b)}}else{var y=!1;k=new window.XMLHttpRequest;k.onreadystatechange=function(){y||4!=k.readyState||(y=!0,d(k.responseText,b))}}k.open("POST",c,!0);k.send(F(h))}function c(a,b){var c;try{var d=D(a).result}catch(q){d=void 0}d||(c=z("%s: %s","UnknownError","An unknown error ocurred"));e(c,b)}function d(a,b){try{var c=
D(a).response}catch(q){c=void 0}if(!c||c.error){a="UnknownError";var d="An unknown error ocurred";c&&c.error&&c.error.code&&c.error.message&&(a=c.error.code,d=c.error.message);d=z("%s: %s",a,d)}e(d,b)}function e(a,b){a&&A("logout",a);b&&"function"==typeof b&&b()}u.ba=function(){"undefined"!==typeof window.OffAmazonPayments&&"undefined"!==typeof window.OffAmazonPayments.Widgets&&"undefined"!==typeof window.OffAmazonPayments.Widgets.Utilities&&window.OffAmazonPayments.Widgets.Utilities.setLoginDomain("");
var c=n.f.getItem(u.g),d=r.A();c&&n.f.removeItem(u.g);!c&&d&&(c=d.access_token);r.w();N()?b(void 0):c&&a(c,void 0)}})();var Oa=["connectedAuth_general"],Pa="profile postal_code payments:widget payments:shipping_address payments:billing_address payments:partial_billing_address payments:autopay_consent profile:user_id prime:benefit_status".split(" ");function Ma(b,a){var c=Qa();return null!==c&&c in b?a?b.lwa_general:b[c]:"/ap/oa"}
function N(){if(u.aa())return!1;var b=Qa();if(null!==b)return-1!==Oa.indexOf(b)}function Na(b,a,c,d,e){a&&(a=document.createElement("a"),a.href=c,""===a.host&&(a.href=a.href),a=a.hostname!==d);return!a&&Ra(b)&&e?N():("undefined"!==typeof window.OffAmazonPayments&&"undefined"!==typeof window.OffAmazonPayments.Widgets&&"undefined"!==typeof window.OffAmazonPayments.Widgets.Utilities&&window.OffAmazonPayments.Widgets.Utilities.createCookie("amazon-pay-connectedAuth","lwa_general",0),!1)}
function Ra(b){var a=!0;return b?(b.c(function(b){-1===Pa.indexOf(b)&&(a=!1)}),a):!1}function Qa(){if(document.cookie&&""!==document.cookie)for(var b=document.cookie.split(";"),a=0;a<b.length;a++){var c=b[a].split("\x3d");if(0===c[0].replace(/ /,"").indexOf("amazon-pay-connectedAuth"))return c[1]}return null}window.amazon=window.amazon||{};window.amazon.Login=window.amazon.Login||{};window.amazon.Login.getClientId=function(){return u.K()};window.amazon.Login.setClientId=function(b){return u.da(b)};
window.amazon.Login.setMerchantID=function(b){return u.ga(b)};window.amazon.Login.setDomain=function(b){return u.o(b)};window.amazon.Login.setLWADomain=function(b){return u.P(b)};window.amazon.Login.setAPIDomain=function(b){return u.F(b)};window.amazon.Login.setSandboxMode=function(b){return u.ia(b)};window.amazon.Login.setSiteDomain=function(b){return n.o(b)};window.amazon.Login.Region=u.V;window.amazon.Login.Metrics=u.u;window.amazon.Login.setRegion=function(b){return u.ha(b)};
window.amazon.Login.setWebflowParams=function(b,a,c){return u.R(b,a,c)};window.amazon.Login.setLanguage=function(b){return u.ea(b)};window.amazon.Login.setLanguageHint=function(b){return u.fa(b)};window.amazon.Login.setUseCookie=function(b){return u.ja(b)};window.amazon.Login.authorize=function(b,a){return u.H(b,a)};window.amazon.Login.logout=function(){return u.ba()};window.amazon.Login.retrieveProfile=function(b,a){return v.O(b,a)};window.amazon.Login.synchronizeSession=function(){return u.ka()};
window.amazon.Login.resumeAuthorize=function(b){return u.ca(b)};"undefined"!==typeof window.OffAmazonPayments&&"undefined"!==typeof window.OffAmazonPayments.Config&&u.R(window.OffAmazonPayments.Config.COE,window.OffAmazonPayments.Config.LEDGER_CURRENCY,window.OffAmazonPayments.Config.ENV);"undefined"!==typeof window.OffAmazonPayments&&"undefined"!==typeof window.OffAmazonPayments.Widgets&&"undefined"!==typeof window.OffAmazonPayments.Widgets.Utilities&&window.OffAmazonPayments.Widgets.Utilities.setLoginDomain("");
if("function"==typeof window.onAmazonLoginReady)window.onAmazonLoginReady();
})();
}
